# Default Configuration file for Modifiers

comm_disabler_texture : &comm-disabler-texture
  texture_type: color
  color: [225, 100, 10]

comm_disabler :
  physical_shape: rectangle
  size: [ 15, 15 ]
  texture: *comm-disabler-texture

sensor_disabler_texture : &sensor-disabler-texture
  texture_type: color
  color: [225, 10, 100]

sensor_disabler :
  physical_shape: rectangle
  size: [ 15, 15 ]
  texture: *sensor-disabler-texture

actuator_disabler_texture : &actuator-disabler-texture
  texture_type: color
  color: [10, 225, 100]

actuator_disabler :
  physical_shape: rectangle
  size: [ 15, 15 ]
  texture: *actuator-disabler-texture

